DELETE FROM daily_plan_items;
DELETE FROM daily_plans;

ALTER TABLE daily_plans DROP COLUMN IF EXISTS available_minutes;
ALTER TABLE daily_plans DROP COLUMN IF EXISTS warning;

ALTER TABLE daily_plans
    ADD COLUMN window_start TIME(0) NOT NULL DEFAULT '09:00',
    ADD COLUMN window_end TIME(0) NOT NULL DEFAULT '18:00',
    ADD COLUMN peak_start TIME(0),
    ADD COLUMN peak_end TIME(0),
    ADD COLUMN free_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN scheduled_work_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN required_minutes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN requested_buffer_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN realized_buffer_minutes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE daily_plans ALTER COLUMN window_start DROP DEFAULT;
ALTER TABLE daily_plans ALTER COLUMN window_end DROP DEFAULT;
ALTER TABLE daily_plans ALTER COLUMN free_minutes DROP DEFAULT;
ALTER TABLE daily_plans ALTER COLUMN scheduled_work_minutes DROP DEFAULT;
ALTER TABLE daily_plans ALTER COLUMN required_minutes DROP DEFAULT;
ALTER TABLE daily_plans ALTER COLUMN requested_buffer_minutes DROP DEFAULT;
ALTER TABLE daily_plans ALTER COLUMN realized_buffer_minutes DROP DEFAULT;

DROP TABLE daily_plan_items;

CREATE TABLE daily_plan_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    daily_plan_id BIGINT NOT NULL,
    rank INTEGER NOT NULL,
    source_task_id BIGINT NOT NULL,
    task_reference_id BIGINT,
    task_title VARCHAR(255) NOT NULL,
    task_priority VARCHAR(32) NOT NULL,
    task_status VARCHAR(32) NOT NULL,
    task_due_date DATE,
    task_estimated_minutes INTEGER,
    must_include BOOLEAN NOT NULL,
    unplaced_reason VARCHAR(32),
    unplaced_minutes INTEGER,
    CONSTRAINT pk_daily_plan_tasks PRIMARY KEY (id),
    CONSTRAINT fk_daily_plan_tasks_daily_plan FOREIGN KEY (daily_plan_id) REFERENCES daily_plans (id),
    CONSTRAINT fk_daily_plan_tasks_task_reference FOREIGN KEY (task_reference_id) REFERENCES tasks (id) ON DELETE SET NULL
);

CREATE INDEX idx_daily_plan_tasks_daily_plan_id ON daily_plan_tasks (daily_plan_id);

CREATE TABLE daily_plan_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    daily_plan_id BIGINT NOT NULL,
    daily_plan_task_id BIGINT,
    kind VARCHAR(32) NOT NULL,
    start_time TIME(0) NOT NULL,
    end_time TIME(0) NOT NULL,
    label VARCHAR(255),
    position INTEGER NOT NULL,
    CONSTRAINT pk_daily_plan_blocks PRIMARY KEY (id),
    CONSTRAINT fk_daily_plan_blocks_daily_plan FOREIGN KEY (daily_plan_id) REFERENCES daily_plans (id),
    CONSTRAINT fk_daily_plan_blocks_daily_plan_task FOREIGN KEY (daily_plan_task_id) REFERENCES daily_plan_tasks (id)
);

CREATE INDEX idx_daily_plan_blocks_daily_plan_id ON daily_plan_blocks (daily_plan_id);

CREATE UNIQUE INDEX uq_daily_plans_owner_id_plan_date ON daily_plans (owner_id, plan_date);
