ALTER TABLE tasks
    ADD COLUMN remaining_effort_minutes INTEGER,
    ADD COLUMN effort_version INTEGER NOT NULL DEFAULT 0;

UPDATE tasks SET remaining_effort_minutes = estimated_minutes;

ALTER TABLE tasks
    ADD CONSTRAINT ck_tasks_remaining_effort_minutes_positive
        CHECK (remaining_effort_minutes IS NULL OR remaining_effort_minutes > 0);

CREATE TABLE daily_plan_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    daily_plan_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    cutoff_time TIME(0),
    free_minutes INTEGER NOT NULL,
    scheduled_work_minutes INTEGER NOT NULL,
    required_minutes BIGINT NOT NULL,
    requested_buffer_minutes INTEGER NOT NULL,
    realized_buffer_minutes INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_daily_plan_revisions PRIMARY KEY (id),
    CONSTRAINT fk_daily_plan_revisions_daily_plan
        FOREIGN KEY (daily_plan_id) REFERENCES daily_plans (id),
    CONSTRAINT uk_daily_plan_revisions_plan_revision
        UNIQUE (daily_plan_id, revision_number)
);

CREATE INDEX idx_daily_plan_revisions_daily_plan_id ON daily_plan_revisions (daily_plan_id);

INSERT INTO daily_plan_revisions (
    daily_plan_id,
    revision_number,
    cutoff_time,
    free_minutes,
    scheduled_work_minutes,
    required_minutes,
    requested_buffer_minutes,
    realized_buffer_minutes,
    created_at
)
SELECT
    id,
    1,
    NULL,
    free_minutes,
    scheduled_work_minutes,
    required_minutes,
    requested_buffer_minutes,
    realized_buffer_minutes,
    created_at
FROM daily_plans;

ALTER TABLE daily_plans
    ADD COLUMN cadence_enabled BOOLEAN,
    ADD COLUMN target_focus_minutes INTEGER,
    ADD COLUMN break_minutes INTEGER,
    ADD COLUMN min_session_minutes INTEGER,
    ADD COLUMN buffer_minutes INTEGER;

CREATE TABLE plan_fixed_break_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    daily_plan_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    start_time TIME(0) NOT NULL,
    end_time TIME(0) NOT NULL,
    CONSTRAINT pk_plan_fixed_break_snapshots PRIMARY KEY (id),
    CONSTRAINT fk_plan_fixed_break_snapshots_daily_plan
        FOREIGN KEY (daily_plan_id) REFERENCES daily_plans (id)
);

CREATE INDEX idx_plan_fixed_break_snapshots_daily_plan_id
    ON plan_fixed_break_snapshots (daily_plan_id);

ALTER TABLE daily_plan_tasks ADD COLUMN revision_id BIGINT;

UPDATE daily_plan_tasks t
SET revision_id = r.id
FROM daily_plan_revisions r
WHERE r.daily_plan_id = t.daily_plan_id;

ALTER TABLE daily_plan_tasks
    ADD COLUMN captured_remaining_effort_minutes INTEGER;

ALTER TABLE daily_plan_tasks
    ADD CONSTRAINT fk_daily_plan_tasks_revision
        FOREIGN KEY (revision_id) REFERENCES daily_plan_revisions (id);

ALTER TABLE daily_plan_tasks DROP CONSTRAINT fk_daily_plan_tasks_daily_plan;
DROP INDEX idx_daily_plan_tasks_daily_plan_id;
ALTER TABLE daily_plan_tasks DROP COLUMN daily_plan_id;
ALTER TABLE daily_plan_tasks ALTER COLUMN revision_id SET NOT NULL;

CREATE INDEX idx_daily_plan_tasks_revision_id ON daily_plan_tasks (revision_id);

ALTER TABLE daily_plan_blocks ADD COLUMN revision_id BIGINT;

UPDATE daily_plan_blocks b
SET revision_id = r.id
FROM daily_plan_revisions r
WHERE r.daily_plan_id = b.daily_plan_id;

ALTER TABLE daily_plan_blocks
    ADD COLUMN outcome VARCHAR(32),
    ADD COLUMN actual_minutes INTEGER,
    ADD COLUMN recorded_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN progress_version INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN reconciled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE daily_plan_blocks
    ADD CONSTRAINT ck_daily_plan_blocks_actual_minutes_non_negative
        CHECK (actual_minutes IS NULL OR actual_minutes >= 0);

ALTER TABLE daily_plan_blocks
    ADD CONSTRAINT fk_daily_plan_blocks_revision
        FOREIGN KEY (revision_id) REFERENCES daily_plan_revisions (id);

ALTER TABLE daily_plan_blocks DROP CONSTRAINT fk_daily_plan_blocks_daily_plan;
DROP INDEX idx_daily_plan_blocks_daily_plan_id;
ALTER TABLE daily_plan_blocks DROP COLUMN daily_plan_id;
ALTER TABLE daily_plan_blocks ALTER COLUMN revision_id SET NOT NULL;

CREATE INDEX idx_daily_plan_blocks_revision_id ON daily_plan_blocks (revision_id);

ALTER TABLE daily_plans
    DROP COLUMN free_minutes,
    DROP COLUMN scheduled_work_minutes,
    DROP COLUMN required_minutes,
    DROP COLUMN requested_buffer_minutes,
    DROP COLUMN realized_buffer_minutes;

CREATE TABLE remaining_effort_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    source_task_id BIGINT NOT NULL,
    task_reference_id BIGINT,
    work_date DATE NOT NULL,
    recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    assessed_remaining_minutes INTEGER,
    CONSTRAINT pk_remaining_effort_checkpoints PRIMARY KEY (id),
    CONSTRAINT fk_remaining_effort_checkpoints_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_remaining_effort_checkpoints_task_reference
        FOREIGN KEY (task_reference_id) REFERENCES tasks (id) ON DELETE SET NULL
);

CREATE INDEX idx_remaining_effort_checkpoints_owner_source
    ON remaining_effort_checkpoints (owner_id, source_task_id);

CREATE TABLE unplanned_work (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    source_task_id BIGINT NOT NULL,
    task_reference_id BIGINT,
    work_date DATE NOT NULL,
    actual_minutes INTEGER NOT NULL,
    recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_unplanned_work PRIMARY KEY (id),
    CONSTRAINT fk_unplanned_work_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_unplanned_work_task_reference
        FOREIGN KEY (task_reference_id) REFERENCES tasks (id) ON DELETE SET NULL,
    CONSTRAINT ck_unplanned_work_actual_minutes_positive CHECK (actual_minutes > 0)
);

CREATE INDEX idx_unplanned_work_owner_work_date ON unplanned_work (owner_id, work_date);
